### PR TITLE
Add GitLab to the list in README.md

### PR DESCRIPTION
**Pull request by abitrolly**

### CODE REVIEW

**Comment by rafaelmardojai** [comment]
Thanks

**Comment by abitrolly** [comment]
@rafaelmardojai thanks to you. It would be update Flatpak store version as well.

image

**Comment by rafaelmardojai** [comment]
@abitrolly For that you need to edit the appstream metadata file: https://github.com/rafaelmardojai/forge-sparks/blob/main/data/com.mardojai.ForgeSparks.metainfo.xml.in.in

**Comment by abitrolly** [comment]
@rafaelmardojai it is already done here https://github.com/rafaelmardojai/forge-sparks/commit/74f7a63912251aec19ad8ca1ba761aea82798cbd but the info is not updated.

**Comment by rafaelmardojai** [comment]
Ah right, sorry forgot. I need to release a new version of the app for the metadata to update. Will do this weekend since GNOME 47 is out.

**Pull request merged**
